# Site settings
title: "Philip J. Freda, Jr., Ph.D., M.S."
description: "Personal academic website"
url: "https://pfreda.github.io"
baseurl: ""

# Author
author:
  name: "Philip J. Freda, Jr., Ph.D., M.S."
  email: "philip.freda@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md

# Collections
collections:
  pages:
    output: true
    permalink: /:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
